### ISSUE TITLE
Не переходит в вкладку "Участники"

### ISSUE THREAD

**Issue by Krissssik** [OshiFugo/FunctionalClans#11]
Could not pass event InventoryClickEvent to FunctionalClans v2.1.5
java.lang.NullPointerException: Cannot load from object array because the return value of "java.util.HashMap.get(Object)" is null
        at ru.oshifugo.functionalclans.sql.Clan.getRoleName(Clan.java:124) ~[FunctionalClans-2.1.5.jar:?]
        at ru.oshifugo.functionalclans.sql.Member.getRankName(Member.java:40) ~[FunctionalClans-2.1.5.jar:?]
        at ru.oshifugo.functionalclans.command.gui_items.members.Members.getMember(Members.java:57) ~[FunctionalClans-2.1.5.jar:?]
        at ru.oshifugo.functionalclans.command.gui_items.members.Members.display(Members.java:78) ~[FunctionalClans-2.1.5.jar:?]
        at ru.oshifugo.functionalclans.command.gui_items.Root.handleClick(Root.java:53) ~[FunctionalClans-2.1.5.jar:?]
        at ru.oshifugo.functionalclans.command.gui_items.ItemsBase.handleClick(ItemsBase.java:172) ~[FunctionalClans-2.1.5.jar:?]
        at xyz.xenondevs.invui.gui.AbstractGui.handleClick(AbstractGui.java:73) ~[FunctionalClans-2.1.5.jar:?]
        at xyz.xenondevs.invui.window.AbstractSingleWindow.handleClick(AbstractSingleWindow.java:69) ~[FunctionalClans-2.1.5.jar:?]
        at xyz.xenondevs.invui.window.AbstractWindow.handleClickEvent(AbstractWindow.java:179) ~[FunctionalClans-2.1.5.jar:?]
        at xyz.xenondevs.invui.window.WindowManager.handleInventoryClick(WindowManager.java:117) ~[FunctionalClans-2.1.5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2947) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]

**Comment by Kepchyk1101** [comment]
Проблема актуальна? Проверьте пожалуйста на версии 2.1.6, либо 2.1.7 (еще не выпущена на spigotmc, но может быть предоставлена в дискорд канале)

**Comment by Krissssik** [comment]
исправило, спасибо!
